### ISSUE TITLE
SDK

### ISSUE THREAD

**Issue by therealcyrex** [vedderb/nrf51_vesc#2]
Hi Benjamin,
can you please upload the SDK?

Best regards
Sasan

**Comment by vedderb** [comment]
I don't think I'm allowed to do that, but you can download it from here:

https://www.nordicsemi.com/Software-and-Tools/Software/nRF5-SDK/Download#infotabs

What I noticed is that the latest SDKs don't seem to support the NRF51 any more, only the nrf52 series. The latest SDK with S130 (and the one I'm using) is 12.3.0

**Comment by therealcyrex** [comment]
thanks a lot
