### ISSUE TITLE
Missing compiled  hex files

### ISSUE THREAD

**Issue by therealcyrex** [vedderb/nrf51_vesc#3]
Hi Benjamin,

can you please add the other hex files too?

**Comment by Val1337** [comment]
Joining to the request.

**Comment by vedderb** [comment]
You can also upload the bin files, which are included. I think all you need to do is change the file name in the upload script and it should work.

Another thing you might be interested in is that the latest version of VESC Tool and the VESC firmware can be used as an SWD programmer, for programming the NRF5 among other chips. If you connect swdio, swclk and gnd (and 3.3v if the NRF has no other supply) from the VESC to the same pins on the NRF51, you can go to the SWD programmer tab in VESC Tool and click connect. If the connection is successful VESC Tool will list compatible firmware for the NRF, and you can pick one to upload. The RX and TX names of the NRF, as well as the xtal freq, are part of the file name. The softdevice will be uploaded too, and there are also firmware included for the NRF52832 and the NRF52840.

**Comment by therealcyrex** [comment]
thanks, I'll give it a try
